### ISSUE TITLE
can't sign in the app

### ISSUE THREAD

**Issue by tingao** [mileswd/mac2imgur#56]
Hey! I used to manually upload a lod of images manually ot img.ur unti yesterday I found you software, it's perfect simple and works!
I'm only having toruble setting it up, I click sign in, open the link but when I hit allow in the img.ur page (after login in my account) the webpage reloads but the app still shows as not logged.
Also I get an error when trying to upload images, sent screenshots with all the problmes in detail.
Hope it helps to solve this problem, can't wait to have an easy app for that, and it looks so nice!
Thanks!

![screen shot 2015-05-08 at 4 12 08 am](https://cloud.githubusercontent.com/assets/12323444/7532059/ea92b0fe-f538-11e4-8924-ddf24b6a513b.png)
![screen shot 2015-05-08 at 4 12 22 am](https://cloud.githubusercontent.com/assets/12323444/7532063/f06cc474-f538-11e4-9f48-8557c26facbd.png)
![screen shot 2015-05-08 at 4 13 31 am](https://cloud.githubusercontent.com/assets/12323444/7532061/edad9218-f538-11e4-84e8-019fcbb6f783.png)
![screen shot 2015-05-08 at 4 12 48 am](https://cloud.githubusercontent.com/assets/12323444/7532067/f79ff7f2-f538-11e4-91c3-daa873d780d8.png)

**Comment by mileswd** [comment]
First of all, thank you for the details you have provided - it makes solving problems much easier :+1:

When you click "allow" in Chrome, you should see something like this:
![](https://i.imgur.com/LmSkoE6.png)
If you don't, handler links may have been disabled, so try enabling them using this: https://support.google.com/chrome/answer/1382847?hl=en-GB

If that still doesn't work, try using Safari to open the link.

For the second issue, the error you are getting (-1001 - "The connection timed out") indicates there is a network issue. This could be caused by many different things, such as:
- Imgur down or blocked
- Unstable internet connection (low bandwidth, overloaded proxy etc)

Try using the application with a different internet connection, if possible, as this should resolve the issue.

Thanks for the feedback and best of luck!

**Comment by tingao** [comment]
wow that was a really fast support! 

I tried thru Safari and it’s working perfectly now, 

Thanks!





—
Henrique Oliveira

**Comment by mileswd** [comment]
No problem, glad I could help.
