### ISSUE TITLE
Logging in doesn't work on OSX 10.11 Developer Beta 4

### ISSUE THREAD

**Issue by AndreasBackx** [mileswd/mac2imgur#68]
This is on OSX 10.11 Beta (15A226f). In Safari it just doesn't do anything but refresh the page when you press 'Allow' on the oauth page of Imgur. On Google Chrome it asks if you want to use mac2imgur for to open the redirect link but then doesn't do anything.

**Comment by mileswd** [comment]
Currently investigating a work around, the new `App Transport Security` functionality in 10.11 doesn't seem to like Imgur's SSL setup...

**Comment by AndreasBackx** [comment]
Yes, trying to upload a screenshot shows the SSL error notification. Could you upload a new release too when it is fixed?

**Comment by mileswd** [comment]
Will do! :+1:

**Comment by mileswd** [comment]
296120678f924dbc87ad7ea87a1677eb56ecb2ae:
- Added a temporary exception to not require forward secrecy for SSL
- Rewritten error handling so that any errors during authentication with Imgur are shown to the user

However, I'm going to keep this issue open until the temporary exception is no longer required.

`Preferences` -> `Check for Updates...` and you're good to go!

**Comment by AndreasBackx** [comment]
Awesomeception!

![Lol](https://i.imgur.com/hGqaCBH.png)

**Comment by mileswd** [comment]
Temporary exception is no longer required, closing issue.
