### ISSUE TITLE
Downscaling from retina doesn't downscale

### ISSUE THREAD

**Issue by josereyes** [mileswd/mac2imgur#82]
It seems like the retina downscaling issue is back.

**Non-Downscaled:**
![Regular](https://i.imgur.com/GsJysVA.png "regular")

**Downscaled:**
![Downscaled](https://i.imgur.com/FNIeFIY.png "downscaled")

**Comment by mileswd** [comment]
How strange - I haven't touched the screenshot downscaling code since October! :confused:

Looking at the images you posted above - it looks like you didn't upload them from mac2imgur itself(?)

If so, this could explain the issue as the original saved screenshot file is left intact (it is not modified whatsoever) whereas the downscaled version is only temporarily kept in memory until it is uploaded to imgur.

**Comment by josereyes** [comment]
@mileswd hmm this is the imgur url that mac2imgur generated. I didn't obtain the url from imgur or elsewhere.

here are a couple other examples that might help:

**Example 1:**
![example 1](https://i.imgur.com/GRPxUSB.png "example 1")

**Example 2:**
![example 2](https://i.imgur.com/ZCCNmlv.png "example 2")

**Comment by mileswd** [comment]
Hm, strange - the new examples you just posted are both appear to be non-retina...

Could you tell me which version of both OS X and mac2imgur you are using?

Also, it'd be great if you could take a look in Console.app to see if mac2imgur is throwing any errors.

Thanks! :)

**Comment by josereyes** [comment]
this was my fault, sorry to bug you @mileswd

**Comment by mileswd** [comment]
No worries! :smile:
